### ISSUE TITLE
How to serve directus from sub-route?

### ISSUE THREAD

**Issue by lebe-dev** [directus-labs/helm-chart#60]
Hello

Thanks for the chart. How to serve directus from sub-route? For example `/help`

**Environment:**
- Kubernetes 1.29 + Nginx Ingress Controller (by F5 group)
- Directus 11.3.2
- Env variable `PUBLIC_URL`: `https://app.company.com/help`

I've tried to do rewrite:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.org/location-snippets: |
      add_header 'Content-Security-Policy' 'upgrade-insecure-requests';
    nginx.org/mergeable-ingress-type: minion
    nginx.org/rewrites: serviceName=lk-app-help-svc rewrite=/
  labels:
    argocd.argoproj.io/instance: lk-experts
  name: lk-app-in
  namespace: platform
spec:
  ingressClassName: nginx
  rules:
      - host: app.company.com
        http:
          paths:
          - backend:
              service:
                name: lk-experts-help-svc
                port:
                  number: 8055
            path: /help
            pathType: ImplementationSpecific
```

What i'm getting:

```
{"errors":[{"message":"Route / doesn't exist.","extensions":{"path":"/","code":"ROUTE_NOT_FOUND"}}]}
```

**Comment by mikesindieiev** [comment]
Hello! That depends on the ingress controller you are using. I see you are using nginx and in my opinion you need something like URL_REWRITE. Here is arbitrary search result from the Internet - https://docs.byteplus.com/en/docs/vke/Configuring-URL-rewrite-rules-for-an-Nginx-Ingress

**Comment by lebe-dev** [comment]
> Hello! That depends on the ingress controller you are using. I see you are using nginx and in my opinion you need something like URL_REWRITE. Here is arbitrary search result from the Internet - https://docs.byteplus.com/en/docs/vke/Configuring-URL-rewrite-rules-for-an-Nginx-Ingress

Yes it does. But i explained it above - Nginx ingress from F5, rewrite works as expected. I don't get it why directus shows me "Route doesn't exist". Also admin panel is unavailable but it enabled by default.

**Comment by mikesindieiev** [comment]
Unfortunately, I am not a big expert of nginx ingress controller. I am using aws ingress controller and it does not have that url rewrite feature at all.
However, I've took a look around the Internet and it seems like you are doing correct redirection. 
Here is the link the f5 nginx example - https://github.com/nginxinc/kubernetes-ingress/tree/v3.7.2/examples/ingress-resources/rewrites
I noticed only one difference - the absence of the trailing slash on redirect endpoint. And, `pathType` is set to `ImplementationSpecific` while original example has it set to `Prefix`.
Additionally, I can add that directus by default redirects `/` to `/admin` with 302 http code but I think that might not be the root cause of the issue

**Comment by mikesindieiev** [comment]
oh, I think I found the root cause of the issue. You are redirecting to `lk-app-help-svc` in the annotation `    nginx.org/rewrites: serviceName=lk-app-help-svc rewrite=/`, however in rules you have defined another service name - `lk-experts-help-svc`
So that might be the reason 
```yaml
rules:
      - host: app.company.com
        http:
          paths:
          - backend:
              service:
                name: lk-experts-help-svc
                port:
                  number: 8055
            path: /help
            pathType: ImplementationSpecific
```
