### ISSUE TITLE
Admin user not created on first install with custom Postgres

### ISSUE THREAD

**Issue by vcanuel** [directus-labs/helm-chart#66]
Hi,

When installing Directus via the Helm chart on Kubernetes with a custom Postgres instance, everything seems to deploy correctly, but the admin user is not created on first install.

Here are the relevant values I’m using:
```yaml
adminEmail: "directus-admin@example.com"
createApplicationSecret: true
applicationSecretName: "directus-application-secret"
databaseEngine: "postgresql"
createPostgresqlSecret: false
createMysqlSecret: false
mysql:
  enableInstallation: false
postgresql:
  enableInstallation: false
  auth:
    existingSecret: "directus-postgresql-secret"
    database: "directus_postgres"
    username: "directus_postgres"
  postgresqlURL: "db-service"
```

I checked the database: directus_roles is correctly populated, but directus_users is empty.

There’s no error during the installation, but once the pod is running, Directus has no user, and I need to create one manually using the CLI:
```bash
npx directus users create \
  --email directus-admin@example.com \
  --password 'XXXXX' \
  --role <UUID_ADMIN_ROLE>
```
Expected behavior: the admin user defined via the adminEmail value and ADMIN_PASSWORD in the secret referenced by applicationSecretName should be created automatically.

Thanks!
